### ISSUE TITLE
DataStore documentation is broken (404s) on mozilla-lockbox.github.io

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/lockbox-datastore#59]
### Steps to reproduce:

1. Go to https://mozilla-lockbox.github.io/lockbox-datastore/
1. Click on any of the links in the sidebar.

### Actual results:

<img width="1440" alt="introduction_-_lockbox_datastore" src="https://user-images.githubusercontent.com/557895/33508922-41928e62-d6b2-11e7-94fd-3d0163638966.png">

<img width="1440" alt="lockbox_datastore_404" src="https://user-images.githubusercontent.com/557895/33508965-93cc8a34-d6b2-11e7-9e64-9d5bf06df564.png">

**Comment by devinreams** [comment]
Thank you for spotting this @pdehaan. I think I have the fix in at #60.
