### ISSUE TITLE
Publish to npm to streamline process

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-datastore#63]
While the only consumers of this module are other Lockbox projects (notably [Lockbox Desktop Extension](/mozilla-lockbox/lockbox-extension) and [Lockbox iOS](/mozilla-lockbox/lockbox-ios)), there is some interest in consuming this module elsewhere.

To make this more easily accessible to others, publishing to `npm` makes sense.  The questions are:

* Should we do this? (consensus is **yes**)
* When should we do this? (consensus is **ASAP**)
* How should we do this (e.g., scoped a la `@mozilla-lockbox/lockbox-datastore`, or global)? (rough consensus is `lockbox-datastore`)

Publication can start as a manual process, but it should move to an automated process soon.

**TASKS**
* [x] Merge #69 
* [ ] document a release procedure
* [ ] publish release "0.2.0"

**Comment by pdehaan** [comment]
I'd vote to just publish as **lockbox-datastore**, unless we think we need scoped packages and are expecting to publish multiple related modules.

**Comment by sandysage** [comment]
## Pros
- it's installed and managed like any other dependency (versus using a GitHub link)
- more attention
- easier to keep up to date (just like any other dependency)

## Cons
- more attention
- lock-step features get more complicated to manage (eg binary keys)

## Timing
- the sooner we do it, it'll be one less complication to keep up to date (streamline process)
- doing it when there isn't a lot of implementation work
- no expected immediate impact to Lockbox (low risk)
