### ISSUE TITLE
Improve error categorization and cross-platform reporting

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-datastore#64]
In service to sync, the categories of errors (i.e., reasons) needs to be expanded to account for the various condition that can occur.  Additionally, the reasons need to be represented in a manner that is understandable to machines and developers across process and platform boundaries.

The additional errors to be handled are covered in [sync](https://mozilla-lockbox.github.io/architecture/sync.html#errors).
 
The machine-actionable "reason" is enumerated and reported via a JavaScript Symbol.  However, this has some drawbacks:

* Symbols do not have a JSON representation
* Symbols do not have a structured clone representation

The above means a Symbol gets lost whenever the error crosses a process boundary, either as a structured clone or JSON stringification.

For the widest compatibility, the `reason` property of `DataStoreError` should be a String instead of a Symbol.  Additionally, for improved diagnostic purposes, this reason string should be conveyed in the error message.

## Related
* #50

**Comment by linuxwolf** [comment]
There should be a well-known separator between the error identifier/category and the rest of the message.  Is `:` ok?

```
LOCKED: the datastore is locked
```

**Comment by linuxwolf** [comment]
@mozilla-lockbox/engineering Updated the issue description to reflect the consensus.

**Comment by linuxwolf** [comment]
mistakenly closed via #71.
