### ISSUE TITLE
Consider object spread in datastore

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-datastore#7]

**Comment by devinreams** [comment]
@linuxwolf Do you still want to consider this? If so we'll move it into the backlog.

**Comment by linuxwolf** [comment]
@devinreams at this point, there isn't a driving need to do it.

**Comment by devinreams** [comment]
OK thanks. Will tidy up and close as 'wontfix' for now.

We can always go back and find/discuss if needed.
