### ISSUE TITLE
Add docs/ and CHANGELOG.md to .npmignore?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/lockbox-datastore#84]
```sh
$ npm init -y
$ npm i lockbox-datastore -S
$ du -sh node_modules/lockbox-datastore # 116K	node_modules/lockbox-datastore

$ tree node_modules/lockbox-datastore

node_modules/lockbox-datastore
├── CHANGELOG.md
├── LICENSE
├── README.md
├── docs
│   ├── CODEOWNERS
│   ├── README.md
│   ├── code_of_conduct.md
│   ├── contributing.md
│   ├── index.md
│   └── install.md
├── lib
│   ├── datastore.js
│   ├── index.js
│   ├── itemkeystore.js
│   ├── items.js
│   ├── localdatabase.js
│   └── util
│       ├── errors.js
│       └── instance.js
├── lockbox-datastore-0.2.0.tgz
└── package.json

3 directories, 18 files
```

It looks like we can shave a quick ~28K from the package:

```sh
$ du -sh node_modules/lockbox-datastore/{CHANGELOG.md,docs}
# 4.0K	node_modules/lockbox-datastore/CHANGELOG.md
#  24K	node_modules/lockbox-datastore/docs
```

**Comment by linuxwolf** [comment]
not opposed to it; care to provide a PR to cover it?  Otherwise we'll prioritize it with other work.

**Comment by pdehaan** [comment]
@linuxwolf PR submitted, #85.

**Comment by pdehaan** [comment]
@linuxwolf Let me know the next time you publish to npm and I can verify the files and size savings. ❤️

**Comment by linuxwolf** [comment]
actually, you could verify now using `npm pack`.

**Comment by pdehaan** [comment]
> actually, you could verify now using npm pack.

Great tip! I never knew about that command!

After 10 minutes of futile debugging, it seems like CHANGELOG is special and will always be included.

> The following paths and files are never ignored, so adding them to **.npmignore** is pointless:
>
> - **package.json**
> - **README** (and its variants)
> - **CHANGELOG** (and its variants)
> - **LICENSE** / **LICENCE**

&mdash; via https://docs.npmjs.com/misc/developers

![lockbox-datastore-tgz](https://user-images.githubusercontent.com/557895/36049662-7feaa3f8-0d98-11e8-928a-a7c95606322c.png)
